name: CI to Docker hub 

on:

  push:

    branches: [ main ]
 

jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
       
      -

        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: |
            user/generic-extension:latest
            ghcr.io/user/generic-extension:latest
            ghcr.io/dnvntr/app:1.0.0
            dnvntr/app:1.0.0

          cache-from: |
                        user/app:cache
                        type=local,src=path/to/dir

      -

        name: Image digest

        run: echo ${{ steps.docker_build.outputs.digest }}
