name: CI to Docker hub 

on:

  push:

    branches: [ main ]
 

jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      -

        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} 
          
      -

        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: dnvntr/generic-extension:latest

      -

        name: Image digest

        run: echo ${{ steps.docker_build.outputs.digest }}
