name: CI to Docker hub 

on:

  push:

    branches: [ main ]
 

jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
      -

        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: |
            dnvntr/generic-extension:latest

          cache-from: type=registry,ref=dnvntr/generic-extension:latest
          cache-to: type=inline

      -

        name: Image digest

        run: echo ${{ steps.docker_build.outputs.digest }}
         
      -
        name: Build And Publish to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "generic-extension"
          heroku_email: "dina.vinter@gmail.com"
          usedocker: true

